### ISSUE TITLE
Update pumpify

### ISSUE THREAD

**Issue by stefnotch** [gulpjs/glob-stream#100]
It'd be great if the pumpify dependency got updated, as the currently used version is rather old.

**Comment by tkellen** [comment]
Is there a feature you're looking for or is this just updating for the sake of updating?

**Comment by stefnotch** [comment]
The `pumpify` version that is being used here has some even older dependencies, which creates a nested node_modules file structure. I'd like to avoid this.

So, in a way, yes, this is an update for the sake of updating.

**Comment by phated** [comment]
Completed by #101
