### ISSUE TITLE
Dependency vulnerability - Glob-parent

### ISSUE THREAD

**Issue by gustavocaspirro-mb** [gulpjs/glob-stream#107]
Hi, I would like to update the glob-parent version in the project.

Below, we have a print of vulnerability presented through of npm audit.

<img width="697" alt="Screen Shot 2021-08-03 at 14 45 27" src="https://user-images.githubusercontent.com/74983760/128061995-3fdc58e9-bad3-45f5-bc7c-578056236d5e.png">

**Comment by phated** [comment]
https://overreacted.io/npm-audit-broken-by-design/
