### ISSUE TITLE
Using `src` globs can be really slow with negation

### ISSUE THREAD

**Issue by necolas** [gulpjs/glob-stream#24]
Trying to use negation in globs can be extremely slow if there are many files in the negated paths (e.g., `node_modules`). For example:

```
[ '**/*.js', '!node_modules/**' ]
```

We're still in the initial phases of a project and while that pattern works, it was causing a lint task to take more than **4s** to finish. Changing the pattern to only use positives (but that means manually adding half a dozen paths and files) brought the task time down to 200ms.

**Comment by UltCombo** [comment]
@contra should we still support regex (post-read) filtering after implementing node-glob's `ignore` option?

**Comment by contra** [comment]
@UltCombo Yeah I think so

**Comment by UltCombo** [comment]
Alright then, I'll have a PR in 30~45mins.

**Comment by contra** [comment]
@UltCombo Any update on this?

**Comment by UltCombo** [comment]
@contra https://github.com/wearefractal/glob-stream/pull/40#issuecomment-81765600

**Comment by thirdcreed** [comment]
nearly have a working PR for this, there's one test broken:
'should return a file name stream with dotfiles negated'
and it's timing out at 2000ms.

Any thoughts on what that might be, for some reason the stream is not emitting anything.
https://github.com/thirdcreed/glob-stream/blob/master/index.js

**Comment by thirdcreed** [comment]
Even when I set the timeout for that test to 15 seconds, it doesn't emit.  It runs in like <1 sec when using glob.sync.  So I know something's up. 

```node -p 'require("glob").sync("/home/thirdcreed/Projects/glob-stream/test/fixtures/*swag",{ignore:["/home/thirdcreed/Projects/glob-stream/test/fixtures/**"],dot:true,cwd: "/home/thirdcreed/Projects/glob-stream/test",cwdbase:false,nonull:false})'```

That returns [ ], like it should.  The ignore actually works, whereas random text in the ignore would allow .swag in, the above command does not; those are the exact parameters being sent into glob.Glob();  

The ignore code is 8 days old, so it could be a bug in there, I'm starting to dive in, but any kind of expertise here would be much appreciated.  Thanks!

**Comment by luengnat** [comment]
any update to this issue? I encounter a similar problem without negation though.

**Comment by contra** [comment]
I think this is the same as another ticket - the ** is being expanded by recursing the fs (this is how globs work). Using `!node_modules` instead of `!node_modules/**` should fix it.
