### ISSUE TITLE
Evaluate Micromatch

### ISSUE THREAD

**Issue by thepian** [gulpjs/glob-stream#44]
While researching globbing alternatives for SocketStream I found the micromatch module. It claims to be a drop-in replacement with a big speedup.

It seems like a good idea to swap minimatch with micromatch.

**Comment by contra** [comment]
@thepian want to send a PR?

**Comment by phated** [comment]
@contra micromatch is the library that @jonschlinkert was talking about a long time ago (before it was written I think)

**Comment by jonschlinkert** [comment]
:+1: that would be great, let me know if I can help
