### ISSUE TITLE
Test refactor

### ISSUE THREAD

**Issue by phated** [gulpjs/glob-stream#72]
Need to bring the tests inline with other repos, switch from `should` to `expect`.

**Comment by phated** [comment]
Assigned to @contra incase he has time to align these tests with the other repositories (vinyl-fs is probably the best example for streams testing)

**Comment by contra** [comment]
@phated What repo should I look at to compare with? vinyl-fs?

**Comment by phated** [comment]
@contra yeah, vinyl-fs has refactored/updated tests that use `mississippi` utilities for testing.

**Comment by phated** [comment]
Thanks @contra. I'm going to reopen because there are some stream tweaks I want to make (e.g. Using pump to handle errors, etc)
