### ISSUE TITLE
Should `create` accept a non-array ignore option

### ISSUE THREAD

**Issue by phated** [gulpjs/glob-stream#77]
We normalize many options passed to `node-glob` and we are combining `ignore` and negative globs so it might make sense to normalize a string for `ignore` to an array (`node-glob` only accepts an array).

Kind of dependent on #74

**Comment by erikkemperman** [comment]
@phated Can't hurt to do it here I suppose, but not strictly necessary with up-to-date glob?
https://github.com/isaacs/node-glob/blob/master/common.js#L31-L32

**Comment by phated** [comment]
Ah, I'll keep it here then.
