### ISSUE TITLE
How can I use it with gulp?

### ISSUE THREAD

**Issue by jenstornell** [gulpjs/glob-stream#93]
I tried this but it did not work.

```js
gulp.task('css', function() {
    gs(
        [
        'site/bricks/global/global.scss',
        'site/bricks/**/*.scss',
        '!site/bricks/global/domain*.scss',
        'site/bricks/global/domain.my-domain.se.scss'
        ])
        .pipe(concat('style.scss'))
        .pipe(sass().on('error', sass.logError))
        .pipe(gulp.dest('assets/css'))
});
```

I replaced `gulp.src` with `gs`. Why I want to use `glob-stream` instead of `gulp.src` is because I want to reinclude my last domain file, which does not work with `gulp.src`.

I did not figure out how to use it in a gulp task. Maybe someone knows?

**Comment by contra** [comment]
Not a replacement for gulp.src - this is a low level library used to build gulp.src and not something you want to use directly
