### ISSUE TITLE
npm audit returns errors.

### ISSUE THREAD

**Issue by GarthDB** [gulpjs/glob-stream#96]
`npm audit` returns high errors with dependencies:

full log at https://gist.github.com/GarthDB/73e3f62e9ee4ccde5d22144b4e4ae163

Updating minimatch will fix it, but https://www.npmjs.com/package/glob hasn't been updated. This error impacts everything using glob-stream including vinyl-fs and gulp itself.

**Comment by GarthDB** [comment]
It looks like the latest version of glob (7.1.2) uses an updated minimatch (^3.0.4)

**Comment by GarthDB** [comment]
The pull request I filed seems to fix the minimatch error, but the dev dependencies need to be updated to fix more of the errors.

**Comment by phated** [comment]
Our ranges already pick up the right versions.

**Comment by GarthDB** [comment]
Thanks @phated
